(function(){
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const money=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+' AWG';
function install(){
 const nav=$('nav'),views=$('views'); if(!nav||!views||$('statementReview')) return;
 const b=document.createElement('button'); b.dataset.route='statementReview'; b.textContent='▤ Bank Statement Review'; nav.insertBefore(b,nav.querySelector('[data-route="audit"]')||null);
 const v=document.createElement('div'); v.id='statementReview'; v.className='view'; v.innerHTML=`<h1>Bank Statement Review</h1><div class="notice"><b>Post-transaction review:</b> upload a downloaded statement export to check completed transactions against thresholds and review rules.</div><div class="grid two"><div class="card"><div class="head">Upload statement</div><div class="body"><p class="muted">Use PDF, CSV, semicolon CSV, tab-delimited TXT, or copied export columns such as date, description, amount, debit, credit, type, and currency.</p><input id="statementFile" type="file" accept=".pdf,.csv,.txt,.tsv,application/pdf,text/csv,text/plain" style="width:100%;padding:8px;height:auto;margin-bottom:10px"><button class="btn primary" id="runStatementReview">Review uploaded statement</button> <button class="btn blue" id="loadStatementDemo">Load demo statement</button><div id="statementStatus" class="notice" style="margin-top:14px;display:none"></div></div></div><div class="card"><div class="head">Review summary</div><div class="body"><div class="row"><span>Transactions reviewed</span><span id="stmtReviewed">0</span></div><div class="row"><span>Threshold hits</span><span id="stmtReportable">0</span></div><div class="row"><span>Review queue</span><span id="stmtInvestigate">0</span></div><div class="row"><span>Highest transaction</span><span id="stmtHighest">0.00 AWG</span></div></div></div></div><br><div class="card"><div class="head">Post-transaction findings</div><div class="body" style="padding:0"><table class="table" id="statementFindings"></table></div></div>`; views.appendChild(v);
 $('runStatementReview').onclick=reviewUpload; $('loadStatementDemo').onclick=demo; render([]);
}
function show(m){const e=$('statementStatus'); if(e){e.style.display='block';e.innerHTML=m}}
function del(line){return [',',';','\t','|'].map(d=>[d,line.split(d).length]).sort((a,b)=>b[1]-a[1])[0][0]}
function amt(v){let s=String(v??'').trim();let neg=/^\(.*\)$/.test(s)||s.includes('-');s=s.replace(/[()A-Za-z$€ƒAWGawgfx\s]/g,'').replace(/,/g,'');let n=parseFloat(s);if(!Number.isFinite(n))n=0;return neg?-Math.abs(n):n}
function parse(txt){const lines=txt.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return[];const d=del(lines[0]),sp=l=>l.split(d).map(x=>x.trim().replace(/^"|"$/g,''));const h=sp(lines[0]).map(x=>x.toLowerCase());const has=h.some(x=>/(date|datum|description|amount|debit|credit|type)/.test(x));if(!has&&d===','&&lines.length>1&&lines.every(l=>l.split(d).length<3))return parseLoose(txt);const idx=(names,f)=>{let i=h.findIndex(x=>names.some(n=>x.includes(n)));return i>=0?i:f};const data=has?lines.slice(1):lines,iDate=has?idx(['date','datum'],0):0,iDesc=has?idx(['description','omschrijving','counterparty','details'],1):1,iAmt=has?idx(['amount','bedrag','value'],2):2,iDebit=has?idx(['debit','withdrawal'],-1):-1,iCredit=has?idx(['credit','deposit'],-1):-1,iType=has?idx(['type','method'],-1):-1;return data.map((line,n)=>{const c=sp(line);let a=0;if(iDebit>=0||iCredit>=0){const db=iDebit>=0?amt(c[iDebit]):0,cr=iCredit>=0?amt(c[iCredit]):0;a=db?-Math.abs(db):Math.abs(cr)}else a=amt(c[iAmt]);const desc=c[iDesc]||'No description provided',kind=((iType>=0?c[iType]:'')+' '+desc);const cash=/cash|contant|atm/i.test(kind);return{row:n+1,date:c[iDate]||'',desc,type:cash?'Cash':'Giro/cashless',amount:Math.abs(a),dir:a<0?'Outgoing':'Incoming'}}).filter(r=>r.amount||r.desc)}
function parseLoose(txt){const dateRe=/\b(\d{4}[-\/]\d{1,2}[-\/]\d{1,2}|\d{1,2}[-\/]\d{1,2}[-\/]\d{2,4})\b/;const amountRe=/[-(]?\b\d{1,3}(?:,\d{3})*(?:\.\d{2})?\b\)?|[-(]?\b\d{4,}(?:\.\d{2})?\b\)?/g;return txt.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,n)=>{const dm=line.match(dateRe);const amounts=[...line.matchAll(amountRe)].map(m=>m[0]).filter(v=>amt(v)!==0);if(!dm||!amounts.length)return null;const last=amounts[amounts.length-1];const a=amt(last);let desc=line.replace(dm[0],'').replace(last,'').replace(/\s{2,}/g,' ').trim()||'PDF statement transaction';const cash=/cash|contant|atm/i.test(desc);return{row:n+1,date:dm[0],desc,type:cash?'Cash':'Giro/cashless',amount:Math.abs(a),dir:a<0?'Outgoing':'Incoming'}}).filter(Boolean)}
function evalRows(rows){const near=rows.filter(r=>r.type!=='Cash'&&r.amount>=450000&&r.amount<500000);return rows.map(r=>{const ind=[],why=[];if(r.type!=='Cash'&&r.amount>=500000){ind.push('130103');why.push('Giro/cashless transaction at or above Afl. 500,000.')}if(r.type==='Cash'&&r.amount>=25000){ind.push('130104');why.push('Cash transaction at or above Afl. 25,000.')}if(near.length>=2&&r.type!=='Cash'&&r.amount>=450000&&r.amount<500000){ind.push('130201');why.push('Repeated near-threshold activity found in this statement.')}return{...r,ind,status:ind.some(i=>i==='130103'||i==='130104')?'Threshold hit':ind.length?'Review':'No hit',why:why.join(' ')||'No threshold or rule hit identified.'}})}
function render(rows){const t=$('statementFindings'); if(!t)return; t.innerHTML='<thead><tr><th>Date</th><th>Description</th><th>Type</th><th class="right">Amount</th><th>Indicators</th><th>Status</th><th>Rationale</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${esc(r.date)}</td><td><b>${esc(r.desc)}</b><br><span class="muted">${esc(r.dir)} · row ${r.row}</span></td><td>${esc(r.type)}</td><td class="right"><b>${money(r.amount)}</b></td><td>${r.ind.length?r.ind.map(i=>`<span class="pill ${i==='130201'?'p-purple':'p-red'}">${i}</span>`).join(' '):'<span class="pill p-green">Clear</span>'}</td><td><span class="pill ${r.status==='Threshold hit'?'p-red':r.status==='Review'?'p-amber':'p-green'}">${r.status}</span></td><td>${esc(r.why)}</td></tr>`).join('')+'</tbody>';$('stmtReviewed').textContent=rows.length;$('stmtReportable').textContent=rows.filter(r=>r.status==='Threshold hit').length;$('stmtInvestigate').textContent=rows.filter(r=>r.status==='Review').length;$('stmtHighest').textContent=money(rows.reduce((m,r)=>Math.max(m,r.amount),0))}
function run(txt,name){const r=evalRows(parse(txt));render(r);show(`<b>${esc(name)} reviewed.</b> ${r.length} transactions checked; ${r.filter(x=>x.status==='Threshold hit').length} threshold hit(s), ${r.filter(x=>x.status==='Review').length} review item(s).`)}
function loadPdfJs(){return new Promise((resolve,reject)=>{if(window.pdfjsLib)return resolve(window.pdfjsLib);const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=()=>resolve(window.pdfjsLib);s.onerror=()=>reject(new Error('PDF parser could not be loaded.'));document.head.appendChild(s)})}
async function pdfText(file){const pdfjs=await loadPdfJs();pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let out=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const content=await page.getTextContent();let lastY=null,line=[];content.items.forEach(item=>{const y=Math.round(item.transform[5]);if(lastY!==null&&Math.abs(y-lastY)>3){out.push(line.join(' ').trim());line=[]}line.push(item.str);lastY=y});if(line.length)out.push(line.join(' ').trim())}return out.filter(Boolean).join('\n')}
async function reviewUpload(){const f=$('statementFile')?.files?.[0];if(!f){show('<b>No file selected.</b> Choose a downloaded statement first.');return}try{show(`<b>${esc(f.name)}</b> is being reviewed.`);if(/\.pdf$/i.test(f.name)||f.type==='application/pdf'){run(await pdfText(f),f.name)}else{const reader=new FileReader();reader.onload=()=>run(String(reader.result||''),f.name);reader.readAsText(f)}}catch(e){show(`<b>Could not review this file.</b> ${esc(e.message||e)}`)}}
function demo(){run('date,description,type,amount\n2026-05-24,Payment to Isthmus Capital SA,Giro,742500\n2026-05-24,Cash deposit,Cash,36000\n2026-05-24,Transfer to Palm Advisory VBA,Giro,499950\n2026-05-24,Second transfer to Palm Advisory VBA,Giro,498750\n2026-05-24,Office rent,Giro,12000','Demo statement')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();