(function(){
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const money=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+' AWG';
const STORE_KEY='axioma_statement_mlco_reviews_v1';
let lastFindings=[];
function getSaved(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||'[]')}catch(e){return[]}}
function setSaved(items){localStorage.setItem(STORE_KEY,JSON.stringify(items));renderSavedReviews()}
function savedId(r){return r.savedId||(r.savedId='BSR-'+Date.now()+'-'+Math.floor(Math.random()*100000))}
function saveRecord(r){if(!r)return;const id=savedId(r),items=getSaved(),now=new Date().toLocaleString();const rec={id,date:r.date,desc:r.desc,type:r.type,amount:r.amount,dir:r.dir,row:r.row,ind:r.ind,status:r.status,decision:r.decision||'',workflowStatus:r.workflowStatus||'',followUp:r.followUp||'',why:r.why||'',updatedAt:now};const ix=items.findIndex(x=>x.id===id);if(ix>=0)items[ix]=rec;else items.unshift(rec);setSaved(items)}
function install(){
 const nav=$('nav'),views=$('views'); if(!nav||!views||$('statementReview')) return;
 const b=document.createElement('button'); b.dataset.route='statementReview'; b.textContent='▤ Bank Statement Review'; nav.insertBefore(b,nav.querySelector('[data-route="audit"]')||null);
 const v=document.createElement('div'); v.id='statementReview'; v.className='view';
 v.innerHTML=`<h1>Bank Statement Review</h1><div class="notice"><b>Post-transaction review:</b> upload a downloaded statement export to check completed transactions against thresholds and review rules.</div><div class="grid two"><div class="card"><div class="head">Upload statement</div><div class="body"><p class="muted">Use PDF, CSV, semicolon CSV, tab-delimited TXT, or copied export columns such as date, description, amount, debit, credit, type, and currency.</p><div id="statementDropZone" style="border:2px dashed #b7cbd4;border-radius:10px;background:#f8fcfe;padding:22px;text-align:center;margin-bottom:10px;cursor:pointer"><b>Drag and drop bank statement here</b><br><span class="muted">PDF, CSV, TXT or TSV. Click this area to select a file.</span></div><input id="statementFile" type="file" accept=".pdf,.csv,.txt,.tsv,application/pdf,text/csv,text/plain" style="width:100%;padding:8px;height:auto;margin-bottom:10px"><button class="btn primary" id="runStatementReview">Review uploaded statement</button> <button class="btn blue" id="loadStatementDemo">Load demo statement</button><div id="statementStatus" class="notice" style="margin-top:14px;display:none"></div></div></div><div class="card"><div class="head">Review summary</div><div class="body"><div class="row"><span>Transactions reviewed</span><span id="stmtReviewed">0</span></div><div class="row"><span>Threshold hits</span><span id="stmtReportable">0</span></div><div class="row"><span>Review queue</span><span id="stmtInvestigate">0</span></div><div class="row"><span>Highest transaction</span><span id="stmtHighest">0.00 AWG</span></div></div></div></div><br><div id="statementCasePanel" class="card" style="display:none"><div class="head">MLCO transaction review</div><div class="body" id="statementCaseBody"></div></div><br><div class="card"><div class="head">Saved MLCO reviews / follow-up queue</div><div class="body" style="padding:0"><table class="table" id="savedStatementReviews"></table></div></div><br><div class="card"><div class="head">Post-transaction findings</div><div class="body" style="padding:0"><table class="table" id="statementFindings"></table></div></div>`;
 views.appendChild(v); $('runStatementReview').onclick=reviewUpload; $('loadStatementDemo').onclick=demo; wireDropZone(); render([]);renderSavedReviews();
}
function show(m){const e=$('statementStatus');if(e){e.style.display='block';e.innerHTML=m}}
function wireDropZone(){const dz=$('statementDropZone'),input=$('statementFile');if(!dz||!input)return;const on=()=>{dz.style.borderColor='#0f679d';dz.style.background='#eaf6ff'},off=()=>{dz.style.borderColor='#b7cbd4';dz.style.background='#f8fcfe'};dz.onclick=()=>input.click();['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();on()}));['dragleave','dragend'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();off()}));dz.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();off();const f=e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files[0];if(f)handleFile(f)});input.addEventListener('change',()=>{if(input.files&&input.files[0])show(`<b>${esc(input.files[0].name)}</b> selected. Click Review uploaded statement to run the review.`)})}
function del(line){return [',',';','\t','|'].map(d=>[d,line.split(d).length]).sort((a,b)=>b[1]-a[1])[0][0]}
function amt(v){let s=String(v??'').trim();let neg=/^\(.*\)$/.test(s)||s.includes('-');s=s.replace(/[()A-Za-z$€ƒAWGawgfx\s]/g,'').replace(/,/g,'');let n=parseFloat(s);if(!Number.isFinite(n))n=0;return neg?-Math.abs(n):n}
function parse(txt){const lines=txt.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return[];const d=del(lines[0]),sp=l=>l.split(d).map(x=>x.trim().replace(/^"|"$/g,''));const h=sp(lines[0]).map(x=>x.toLowerCase());const has=h.some(x=>/(date|datum|description|amount|debit|credit|type)/.test(x));if(!has&&d===','&&lines.length>1&&lines.every(l=>l.split(d).length<3))return parseLoose(txt);const idx=(names,f)=>{let i=h.findIndex(x=>names.some(n=>x.includes(n)));return i>=0?i:f};const data=has?lines.slice(1):lines,iDate=has?idx(['date','datum'],0):0,iDesc=has?idx(['description','omschrijving','counterparty','details'],1):1,iAmt=has?idx(['amount','bedrag','value'],2):2,iDebit=has?idx(['debit','withdrawal'],-1):-1,iCredit=has?idx(['credit','deposit'],-1):-1,iType=has?idx(['type','method'],-1):-1;return data.map((line,n)=>{const c=sp(line);let a=0;if(iDebit>=0||iCredit>=0){const db=iDebit>=0?amt(c[iDebit]):0,cr=iCredit>=0?amt(c[iCredit]):0;a=db?-Math.abs(db):Math.abs(cr)}else a=amt(c[iAmt]);const desc=c[iDesc]||'No description provided',kind=((iType>=0?c[iType]:'')+' '+desc);const cash=/cash|contant|atm/i.test(kind);return{row:n+1,date:c[iDate]||'',desc,type:cash?'Cash':'Giro/cashless',amount:Math.abs(a),dir:a<0?'Outgoing':'Incoming'}}).filter(r=>r.amount||r.desc)}
function parseLoose(txt){const dateRe=/\b(\d{4}[-\/]\d{1,2}[-\/]\d{1,2}|\d{1,2}[-\/]\d{1,2}[-\/]\d{2,4})\b/;const amountRe=/[-(]?\b\d{1,3}(?:,\d{3})*(?:\.\d{2})?\b\)?|[-(]?\b\d{4,}(?:\.\d{2})?\b\)?/g;return txt.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,n)=>{const dm=line.match(dateRe);const amounts=[...line.matchAll(amountRe)].map(m=>m[0]).filter(v=>amt(v)!==0);if(!dm||!amounts.length)return null;const last=amounts[amounts.length-1];const a=amt(last);let desc=line.replace(dm[0],'').replace(last,'').replace(/\s{2,}/g,' ').trim()||'PDF statement transaction';const cash=/cash|contant|atm/i.test(desc);return{row:n+1,date:dm[0],desc,type:cash?'Cash':'Giro/cashless',amount:Math.abs(a),dir:a<0?'Outgoing':'Incoming'}}).filter(Boolean)}
function evalRows(rows){const near=rows.filter(r=>r.type!=='Cash'&&r.amount>=450000&&r.amount<500000);return rows.map(r=>{const ind=[],why=[];if(r.type!=='Cash'&&r.amount>=500000){ind.push('130103');why.push('Giro/cashless transaction at or above Afl. 500,000.')}if(r.type==='Cash'&&r.amount>=25000){ind.push('130104');why.push('Cash transaction at or above Afl. 25,000.')}if(near.length>=2&&r.type!=='Cash'&&r.amount>=450000&&r.amount<500000){ind.push('130201');why.push('Repeated near-threshold activity found in this statement.')}return{...r,ind,status:ind.some(i=>i==='130103'||i==='130104')?'Threshold hit':ind.length?'Review':'No hit',why:why.join(' ')||'No threshold or rule hit identified.',decision:'',workflowStatus:'',followUp:''}})}
function render(rows){lastFindings=rows;const t=$('statementFindings');if(!t)return;t.innerHTML='<thead><tr><th>Date</th><th>Description</th><th>Type</th><th class="right">Amount</th><th>Indicators</th><th>Status</th><th>Rationale</th><th>MLCO action</th></tr></thead><tbody>'+rows.map((r,i)=>{const active=r.status==='Threshold hit'||r.status==='Review';return`<tr ${active?`data-open-stmt="${i}" style="cursor:pointer"`:''}><td>${esc(r.date)}</td><td><b>${esc(r.desc)}</b><br><span class="muted">${esc(r.dir)} · row ${r.row}</span></td><td>${esc(r.type)}</td><td class="right"><b>${money(r.amount)}</b></td><td>${r.ind.length?r.ind.map(i=>`<span class="pill ${i==='130201'?'p-purple':'p-red'}">${i}</span>`).join(' '):'<span class="pill p-green">Clear</span>'}</td><td><span class="pill ${r.status==='Threshold hit'?'p-red':r.status==='Review'?'p-amber':'p-green'}">${r.status}</span>${r.decision?`<br><span class="pill p-green">${esc(r.decision)}</span>`:''}${r.workflowStatus?`<br><span class="muted">${esc(r.workflowStatus)}</span>`:''}</td><td>${esc(r.why)}</td><td>${active?`<button class="btn blue" data-open-stmt="${i}">Open review</button>`:'<span class="muted">No action</span>'}</td></tr>`}).join('')+'</tbody>';$('stmtReviewed').textContent=rows.length;$('stmtReportable').textContent=rows.filter(r=>r.status==='Threshold hit').length;$('stmtInvestigate').textContent=rows.filter(r=>r.status==='Review').length;$('stmtHighest').textContent=money(rows.reduce((m,r)=>Math.max(m,r.amount),0));wireFindingClicks()}
function renderSavedReviews(){const t=$('savedStatementReviews');if(!t)return;const items=getSaved();t.innerHTML='<thead><tr><th>Saved</th><th>Description</th><th class="right">Amount</th><th>Decision</th><th>Follow-up</th><th>Action</th></tr></thead><tbody>'+(items.length?items.map(r=>`<tr><td>${esc(r.updatedAt||'')}</td><td><b>${esc(r.desc)}</b><br><span class="muted">${esc(r.date)} · ${esc(r.type)} · row ${esc(r.row)}</span></td><td class="right"><b>${money(r.amount)}</b></td><td><span class="pill ${r.decision==='FIU report ready'?'p-red':r.decision==='Under MLCO review'?'p-amber':'p-green'}">${esc(r.decision||'Pending')}</span><br><span class="muted">${esc(r.workflowStatus||'')}</span></td><td>${esc(r.followUp||'N/A')}</td><td><button class="btn blue" data-open-saved="${esc(r.id)}">Open saved</button></td></tr>`).join(''):`<tr><td colspan="6"><span class="muted">No saved MLCO reviews yet. Select an MLCO decision to add items to this register.</span></td></tr>`)+'</tbody>';document.querySelectorAll('[data-open-saved]').forEach(el=>{el.onclick=()=>openSaved(el.dataset.openSaved)})}
function wireFindingClicks(){document.querySelectorAll('[data-open-stmt]').forEach(el=>{el.onclick=e=>{e.stopPropagation();openFinding(Number(el.dataset.openStmt))}})}
function nextDate(){const d=new Date();d.setDate(d.getDate()+5);return d.toISOString().slice(0,10)}
function nextSteps(r){if(!r.decision)return `<div class="notice"><b>Next step:</b> select an MLCO action above.</div>`;if(r.decision==='FIU report ready')return `<div class="notice"><b>Next step: FIU package queue.</b><br>Prepare the reporting package and keep the supporting evidence with the case.<div class="check">Bank-statement transaction extract retained.</div><div class="check">CDD/KYC, UBO, invoice/agreement, and rationale to be attached.</div><div class="check">Generate the FIU draft package only after MLCO approval.</div></div>`;if(r.decision==='Under MLCO review')return `<div class="notice"><b>Next step: follow-up review.</b><br>Keep the transaction open until the MLCO completes the evidence review.<div class="row"><span>Follow-up date</span><span><input id="stmtFollowDate" type="date" value="${esc(r.followUp||nextDate())}" style="height:32px"></span></div><div class="check">Request or review missing supporting documents.</div><div class="check">Compare the transaction with the client profile and expected activity.</div><br><button class="btn amber" id="stmtSaveFollow">Save follow-up</button></div>`;return `<div class="notice"><b>Next step: close with rationale.</b><br>No report is prepared based on the documented MLCO rationale.<div class="check">Closure decision retained in the case file.</div><div class="check">Evidence retained for audit trail and supervisory review.</div></div>`}
function openFinding(i){const r=lastFindings[i],panel=$('statementCasePanel'),body=$('statementCaseBody');if(!r||!panel||!body)return;panel.style.display='block';body.innerHTML=`<div class="grid two"><div><div class="row"><span>Date</span><span>${esc(r.date)}</span></div><div class="row"><span>Description</span><span>${esc(r.desc)}</span></div><div class="row"><span>Type</span><span>${esc(r.type)}</span></div><div class="row"><span>Amount</span><span>${money(r.amount)}</span></div><div class="row"><span>Indicators</span><span>${r.ind.map(x=>`<span class="pill ${x==='130201'?'p-purple':'p-red'}">${x}</span>`).join(' ')}</span></div><div class="row"><span>Current status</span><span>${esc(r.status)}</span></div><div class="row"><span>Decision</span><span>${esc(r.decision||'Pending MLCO decision')}</span></div></div><div><b>MLCO rationale</b><textarea id="stmtMlcoNote" style="width:100%;height:126px;margin-top:8px;padding:10px;border:1px solid #ccd9df;border-radius:6px">${esc(r.why)}${r.decision?'':' Review supporting documents, client profile, source of funds, counterparty and business rationale before deciding whether to report to FIU Aruba.'}</textarea><br><br><button class="btn primary" data-stmt-report="${i}">Mark for FIU report</button> <button class="btn amber" data-stmt-review="${i}">Keep under review</button> <button class="btn" data-stmt-clear="${i}">No report after review</button> <button class="btn blue" id="closeStmtPanel">Close</button><br><br>${nextSteps(r)}</div></div>`;panel.scrollIntoView({behavior:'smooth',block:'start'});const reportBtn=body.querySelector('[data-stmt-report]'),reviewBtn=body.querySelector('[data-stmt-review]'),clearBtn=body.querySelector('[data-stmt-clear]'),followBtn=body.querySelector('#stmtSaveFollow');if(reportBtn)reportBtn.onclick=()=>setDecision(i,'FIU report ready');if(reviewBtn)reviewBtn.onclick=()=>setDecision(i,'Under MLCO review');if(clearBtn)clearBtn.onclick=()=>setDecision(i,'No report');if(followBtn)followBtn.onclick=()=>saveFollow(i);$('closeStmtPanel').onclick=()=>closePanel(i)}
function openSaved(id){const r=getSaved().find(x=>x.id===id),panel=$('statementCasePanel'),body=$('statementCaseBody');if(!r||!panel||!body)return;panel.style.display='block';body.innerHTML=`<div class="notice"><b>Saved MLCO review record.</b><br>This record is stored in this browser's local storage for the demo.</div><div class="grid two"><div><div class="row"><span>Date</span><span>${esc(r.date)}</span></div><div class="row"><span>Description</span><span>${esc(r.desc)}</span></div><div class="row"><span>Type</span><span>${esc(r.type)}</span></div><div class="row"><span>Amount</span><span>${money(r.amount)}</span></div><div class="row"><span>Indicators</span><span>${(r.ind||[]).map(x=>`<span class="pill ${x==='130201'?'p-purple':'p-red'}">${x}</span>`).join(' ')}</span></div><div class="row"><span>Decision</span><span>${esc(r.decision||'Pending')}</span></div><div class="row"><span>Workflow</span><span>${esc(r.workflowStatus||'')}</span></div><div class="row"><span>Saved</span><span>${esc(r.updatedAt||'')}</span></div></div><div><b>MLCO rationale</b><textarea style="width:100%;height:126px;margin-top:8px;padding:10px;border:1px solid #ccd9df;border-radius:6px" readonly>${esc(r.why||'')}</textarea><br><br>${nextSteps(r)}<button class="btn blue" id="closeStmtPanel">Close</button></div></div>`;panel.scrollIntoView({behavior:'smooth',block:'start'});$('closeStmtPanel').onclick=()=>panel.style.display='none'}
function setDecision(i,decision){const note=$('stmtMlcoNote')?.value||'';const r=lastFindings[i];if(r){r.decision=decision;r.why=note;if(decision==='FIU report ready')r.workflowStatus='FIU package queue';else if(decision==='Under MLCO review'){r.workflowStatus='Follow-up pending';r.followUp=r.followUp||nextDate()}else r.workflowStatus='Closed - no FIU report';saveRecord(r)}render(lastFindings);show(`<b>${esc(r?.desc||'Transaction')}</b> marked as ${esc(decision)} and saved to the MLCO review register.`);openFinding(i)}
function saveFollow(i){const r=lastFindings[i],d=$('stmtFollowDate')?.value;if(r){r.followUp=d;r.workflowStatus='Follow-up set for '+d;saveRecord(r);render(lastFindings);show(`<b>${esc(r.desc)}</b> follow-up saved for ${esc(d)}.`);openFinding(i)}}
function closePanel(i){const p=$('statementCasePanel');if(p)p.style.display='none';const r=lastFindings[i];show(`<b>${esc(r?.desc||'Transaction')}</b> review panel closed. ${r?.decision?'Decision saved: '+esc(r.decision)+'.':'No decision selected yet.'}`)}
function run(txt,name){const r=evalRows(parse(txt));render(r);$('statementCasePanel')&&($('statementCasePanel').style.display='none');show(`<b>${esc(name)}</b> reviewed. ${r.length} transactions checked; ${r.filter(x=>x.status==='Threshold hit').length} threshold hit(s), ${r.filter(x=>x.status==='Review').length} review item(s).`)}
function loadPdfJs(){return new Promise((resolve,reject)=>{if(window.pdfjsLib)return resolve(window.pdfjsLib);const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=()=>resolve(window.pdfjsLib);s.onerror=()=>reject(new Error('PDF parser could not be loaded.'));document.head.appendChild(s)})}
async function pdfText(file){const pdfjs=await loadPdfJs();pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let out=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const content=await page.getTextContent();let lastY=null,line=[];content.items.forEach(item=>{const y=Math.round(item.transform[5]);if(lastY!==null&&Math.abs(y-lastY)>3){out.push(line.join(' ').trim());line=[]}line.push(item.str);lastY=y});if(line.length)out.push(line.join(' ').trim())}return out.filter(Boolean).join('\n')}
async function handleFile(f){try{show(`<b>${esc(f.name)}</b> is being reviewed.`);if(/\.pdf$/i.test(f.name)||f.type==='application/pdf'){run(await pdfText(f),f.name)}else{const reader=new FileReader();reader.onload=()=>run(String(reader.result||''),f.name);reader.readAsText(f)}}catch(e){show(`<b>Could not review this file.</b> ${esc(e.message||e)}`)}}
function reviewUpload(){const f=$('statementFile')?.files?.[0];if(!f){show('<b>No file selected.</b> Choose a downloaded statement first or drag and drop it into the upload area.');return}handleFile(f)}
function demo(){run('date,description,type,amount\n2026-05-24,Payment to Isthmus Capital SA,Giro,742500\n2026-05-24,Cash deposit,Cash,36000\n2026-05-24,Transfer to Palm Advisory VBA,Giro,499950\n2026-05-24,Second transfer to Palm Advisory VBA,Giro,498750\n2026-05-24,Office rent,Giro,12000','Demo statement')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();